version: "3"

services:
    openchat:
        image: openai/openchat:latest
        container_name: openchat
        ports:
            - 3000:3000
		restart: always
        environment:
            OPENAI_API_KEY: ${OPENAI_API_KEY}
			CODE: ${CODE}